web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php-fpm
php-fpm:
    image: php:7-fpm
    volumes:
        - ./:/var/www/html